-- AlterTable
ALTER TABLE "Shop" ADD COLUMN     "agreedToBlacklist" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "agreedToTerms" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "businessName" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "city" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "country" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "deliveryFee" TEXT DEFAULT 'none',
ADD COLUMN     "deliveryTime" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "email" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "isGICertified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isHandmade" TEXT NOT NULL DEFAULT 'Mixed',
ADD COLUMN     "offersCustomization" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "orderProcessing" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "ownerName" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "packagingType" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "paymentMethods" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "phoneNumber" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "pickupOptions" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "pricingStructure" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "productCategories" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "returnPolicy" TEXT DEFAULT 'none',
ADD COLUMN     "state" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "stockAvailability" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "vendorType" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "website" TEXT NOT NULL DEFAULT 'none',
ADD COLUMN     "zipCode" TEXT NOT NULL DEFAULT 'none',
ALTER COLUMN "description" DROP DEFAULT,
ALTER COLUMN "shopTiming" DROP DEFAULT,
ALTER COLUMN "workingDays" DROP DEFAULT;
